analyzer:
  exclude:
    - test/mocks.mocks.dart
    - lib/core/ui/voltz_icons.dart
  errors:
    argument_type_not_assignable: false
    invalid_assignment: false
    asset_does_not_exist: false

linter:
  rules:
    avoid_classes_with_only_static_members: false
    require_trailing_commas: false
    constant_identifier_names: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    sort_pub_dependencies: false
    overridden_fields: false
    avoid_void_async: false
    prefer_initializing_formals: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
    always_use_package_imports: true
    avoid_function_literals_in_foreach_calls: false
    prefer_const_constructors_in_immutables: false
    unnecessary_null_checks: false
